import rosalind

rosalind.say_hi()

s = 'AGCCTACTTCTGTGGGTTAGTGTCATAGAATCGGTACACGACAGGTGACAGTAGGGTTTTGAAGGTATAGATCGTGACGCGTAGCCACCGAATGGATTAATTTACCCAAGGGCCAGGTAGAGACTGTTGTCTCCCGATACCATGTCGAGAGTGCCTGAAGTATAGGCGTTCGTGCTTTCCTCGGTGTACAAAAGGTGGCCCGGAGTTTTTCTAGTACCCTCTTCTAAACCTCCCCAAAATCTACTCTGATCCCATTCTACATTCTCGCATTGTGCGGGAGCTTTGATTTGGGAAATATGGCCTCTAGCTACCTACATGATTATTGAGTGTAACTCCCGATGCGGACACGGTCCATAATTTTAGGTTGGCGGTCCACATGTACAGGAGCGGCACCAACACAGGGTTTGACGGCTCTCTACACAGGTGGTCCACCCTGTCAGAGCGCTCTGTGATCGTGCGCTTCGTGCGCAGATGTAACGCTGGAAGTAGAGGGCGTCAAGCTGACGACTTCTTTGTACGCAAGTTAGAGTACGCACAAGGTCTCACTTCATACCGGATCGTGGAGAACCATTCATGAAATTACCCGCGCTACGTATACCGACGAGCATACCGAACAAATGGAGACTTAGCGACCCTGTACCTCGTAAAAAAACATCGTGTGGCGTCGGCAACTGGCGTTTTGTACACCGGCTGTCAGTTTTCTTGGCCTACGGGTAGCATCCCGCCCAGCACTGAAAGCAAACGTTCACTCGACAAAGAGACCTTCGAGTCCCCAACCAAGTCAATAATGTTCCACTGGCACTCTCGGTCGGGGGATTAGAGATCAGTCGCTCGATTAGGATTAACATTCGCTGTTCTTAAGATACCCGGTGGTATGTTTTTGTTTCGCACGTTTGGAGGCTAGTGAATGATGAGATTCCGCAT'
def dnakeys(s):
    d = {}
    for each in s:
        if each in d:
            d[each] = d[each]+1
        else:
            d[each] = 1
    print d['A'], d['C'], d['G'], d['T']

dnakeys(s)